plugins:
  - html

env:
  es6: true
  node: true

parserOptions:
  ecmaVersion: 6
  sourceType: module

rules:
  semi: [error, always]
  no-extra-semi: error
  semi-spacing: error
  comma-spacing: error
  no-shadow: warn
  no-unused-vars: warn
  no-use-before-define: [error, nofunc]

  # Disabled:
  no-underscore-dangle: off
  quotes: off
  strict: off
